apiVersion: v2
appVersion: 8.9.0
description: Um chart Helm para instalar o Elastic Stack (Elasticsearch, Kibana, Fleet)
  baseado nos manifestos fornecidos.
name: elk-chart
type: application
version: 0.1.0
